stages:
  - build
  - push

variables:
  GIT_SSL_NO_VERIFY: "true"
  IMAGE_NAME: "registry.enpace.local/tiktai/handler"
  IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"

# Use Docker-in-Docker
# services:
#   - docker:dind

before_script:
  - podman info

build-image:
  stage: build
  image: quay.io/podman/stable:latest
  script:
    - podman build -t $IMAGE_NAME:$IMAGE_TAG . # needs fixing
    - podman images
  artifacts:
    paths:
      - dora-handler
    expire_in: 1 hour
  only:
    - branches

push-image:
  stage: push
  image: quay.io/podman/stable:latest
  script:
    - echo "$CI_REGISTRY_PASSWORD" | podman login registry.enpace.local -u "$CI_REGISTRY_USER" --password-stdin
    - podman push $IMAGE_NAME:$IMAGE_TAG
  only:
    - branches
  dependencies:
    - build-image