name: Build
on:
    push:
      branches:
      - main
      tags:
        - 'v*'
    pull_request:
      types: [opened, synchronize, reopened]

permissions:
  contents: read
  packages: write

jobs:  
  ko-build:
    uses: metraction/github-actions/.github/workflows/ko-build.yaml@0.0.4
    secrets: inherit
    
  push-helm-chart:
    uses: metraction/github-actions/.github/workflows/helm-push.yaml@0.0.4
    needs: [ko-build]
    with:
      chart_dir: helm/handler
      chart_name: handler
      destination: .
      registry: oci://ghcr.io/metraction/charts
    secrets: inherit