name: Push Helm Chart

on:
  push:
    branches:
    - main
    - 'H-19/*'
    tags:
      - 'v*'

jobs:
  push-helm-chart:
    uses: metraction/github-actions/.github/workflows/helm-push.yaml@main
    with:
      chart_dir: helm/handler
      chart_name: handler
      destination: .
      registry: oci://ghcr.io/metraction/charts
    secrets: inherit
