apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "handler.fullname" . }}-config
data:
  .image-handler.yaml: |
    prometheus:
        url: https://prometheus.enpace.local
        # url: http://localhost:9090
        interval: {{ .Values.prometheus.fetchInterval }}
    crane:
        images_whitelist: 
        - registry.enpace.local\/tiktai\/handler.*
        registry_username: "$ENPACE_REGISTRY_USERNAME"
        registry_password: "$ENPACE_REGISTRY_PASSWORD"    
    httpServer:
        port: {{ .Values.httpPort }}
