---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: enpace-registry-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ENPACE_REGISTRY_PASSWORD: AgAoIY4j5IkjoOi3m0G0hy/NJ/h329a9+OYZ9zhdsx6Pk3X+4NU6Z1irPfD7bVGKyMOFfz4gZ2PttIDPlrRL94gkMIXlRCQ3bdQPtnTwcKg4QIf/PAXYnClse07HTFGKIibud/gijHOgcUxFa23vrsx0BML0GzMowWmwKwSBG2el9F72uLvgIticHGOtji/zwE5QSdYrrpJcjYhztpwR1cJiW/evKxhREQ/yrvRP+U+1GLilxNq7SNJc96OvR7iGHvxNp0QlnrfRDVN57zb5iAFu0tg8a6wJDXVQItua1TCQW5hlvllCoH2rpWuNlouOR/wZQSSzhxkk+HQ0vsxY8wHdOo/r/Xt36Ra6VNbY/4DL2Am7Dv/Vl1tnJklvNl3TTlDNHZ+xAPltKVvvpE+qj6PywsheNUlOl3M6lYsFDBZSAdbCVKY3K6XlUQsUcoD7rJxlrbM6fOX0dBEhJpLMOT1ReVunmAEpZf37hUp8m84bBjqJVnZe6Yp1/USgquAzxcZ/+M28YO5LrNOhw5bKXM8FzzO7hJwjnjsLkLSiBh6+qTLySRvJTuWqfmknKg+YMFrdA1SAV+YOiGh/hRkSu68UKkNvwi8rEuwRY8DKKYK+2FJwuz/6bwT0HGTJrPNWp8bS/ItVT5n9Oai/Q6tuwP5a4kOrS23ESKUguleknqZiHdyltFA/fsVnqm5URyZfrRyGY9LcMD/EWjOfzqM6w328A5tlPg==
    ENPACE_REGISTRY_USERNAME: AgCHbo7+CoFYviVnl6l6WopYEWMI0vV6J2UwTFDvwLbfp5+cubSf313m0JA20HlNNEFRRX8/oZPYKFsvO7DJYn6fQT9dyQiigSLTeBLCQYbJJYwrEa68n2u+qXIHVeDc53TcP6bvjqKAdTgU4W9od+GRziuc+9oppjuxjSrC4lwecSKLsDWluDEsuV253W7iR5V2Jv5v0nb3mb/e0srcUVrFR7hDARqucniX8A01EEby9zKxJnwypB14p/sJ83q5QjRvyNy1VmxBo3VYKWbh7Isi3Aj9Q//tHl0QdTSgMFUooDf4wWtI49tgm2qyrb3MSAMAG4JC17gvOTJbgQ6aJwvVHiT/lNGQ/F+7unjovPbVabV6HjtidW9YFp5aDpgwf6LAhGHpX7vAIU8jFkZaalUgBMqR7zk+GdUxJ7yVIY3WKslnqUEJYS+B477kAIDxArX5eEcqkTJiH0NCyvy+nvAQQxfezOWRJXz0INdr1YXq+9OuLUVRoqulv6w9NVmjipuIw8oi85k+U4wa3LKFb95FPukmBsHo5vQHJLAZ0i03jepVuJkNTo09f8Y0kCVlaNK6DmTnntMIpk0QkUtDg2TVah3STkSYfrbLY2iY+PiEgq5MpejZyRlu+vgxn2+bWbwjpj4FhdQ4OLoOEURtUhgNIZvclk3UHjuYXjcbr8tP29l4W6mCSwnDSvnqHgBMkQi5pX7lRcQA
  template:
    metadata:
      name: enpace-registry-secret
      namespace: {{ .Release.Namespace }}

