---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: enpace-registry-secret
  namespace: default
spec:
  encryptedData:
    ENPACE_REGISTRY_PASSWORD: AgAI72ko3N5zUUb3i+QP8QtLftE4C/FhK5V1r2ikjmJiq5ph+EN3btJ+0ng920VWsK3JvXtcmGCWjdEWxH7/nYahNJavCTZ4Rofa8V2LxAeuF24Vu7E4ZX9FLUrdmUyIFiAjxmJT1QNjPrBetIg7v8RVXvgeYwHp7Y3/xz8j/A48pICfD5S+rP9COfEPB3uPXHVdY36RRURMGctxIeQirAlYCrktkA9ZXq/xEGZ57raxWjhA/XRWWB0Wggrnh7ao4I0txV5LOnnXWXsCEg1q9otTsgM7p1zxmMTDq1uZs3fgb1BuLx0OR4N979CAvYWlGCVk/AnU/A+Qu6NeWK26lhjLX0yhMRL8xxUm2CxLg1XpEkA8pPkbptwNYQGhkZnplxv3G6LLYuUz9ALl8QjJexvqw6ozrxLDcXe3HbRathwDIwnmSbkKSftsv+7UumQjhUCi+7w4BLAASnJbcgqMZG7Z+ZTFop3zRivIxZU4yI5yyCJgE8X+109MJu+Y9Rv7qCglPd6mRMhYYOAOcOThTn6mAY3wHVSdNOv3McltZ3u6rBarZkypMc7ZEVOFkQADXQRKa6s1pK55bGtXo40JkDwgN7nUOl3zMq2u0tV3+OszEwq3zkUKxfivbX2IwljfzAmXVXnAA+H1zRshGvGizQpCoVHNqNCMKFO95knvOs8C5I75TrvouPemM1/ALRq7oCmbdJdCO3mnYPgWl8zM1y7xNb119g==
    ENPACE_REGISTRY_USERNAME: AgBLvzG+pyKwPijm9KoSg+CRRaUCdDM70mhtSoiBgea9Wkv5PZReZqISSA824nVMn/1lAn5hAeP1eW+FwWHzDrajtTGq6vsp+5qbNR4c6LIgPzxhWofQ+3mGlwXY1YSy6yZPr7dmq3eQqLW1oczXdM4mDWNrs1FODZ6ANe8YKWKrUiPgOu5hLrnboX3Om1AgI6sEkfL04Bh17ZyWk4KKkvLRt8FtCr5HBqEmtLrmaGh81NwOXZ+BV2MBOln2i/v9OMJeWPWWaLtPs02YMYbXj+VArFw80U24Fpn80rxVilp4bgRChbZJbrU2pEjQYa3VbqBRPT6w8LO+7nzXSdic8jcYsOyveW/1XAdKQ//jQEqz/r/0Ecws0S0dXhDo3hCn5eR5A3XMtk3ZDr14JAVL2no8H1/TqoawOdZWI5lrsi6XGKABnBNmJyfKTXfNkk1vaGpEQqOnHGH1GyXNHsrJ47FFh9NXcehke2eptVrnEUyt29E3CUwCgntv0oJN36R09qOb5nVXPTT2p0RGnIQw4mRjZmOrC2JJ7TVyb7ITJk7XHv3IEdyWcG5yTzUfwqA1In9lzF6u6kOdO6+hEeTMoFlqRMr3xNZNC31RG/Gqc5BwOlmXOnQ+RmUd/6KjwQZ36Vn9UA2B7ratfasMViGfgBy+oojYCFk+bN9P8xtWbl/OjdQJDNyUy/Z1hyiHeMYm8GEGd5r0XM/J
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: enpace-registry-secret
      namespace: default
