apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: enpace-registry
  namespace: {{ .Release.Namespace}}
spec:
  encryptedData:
    .dockerconfigjson: AgCm2yERN2hrgzRnuNfrbDnZ3aFn3JAWiuvi53QiX0mnFH2lmeFC0Ul5uWmdPIrzoK0wuhwf0BhT7twvcgSwDDxx8GBb+iPHJOPf0QUcSB1kKdZwq5/QzI5r8nUVh89tLP4utT4BHGxlzvXzXB03hn/gg9Db6GJMOw/5GGaqJKsSb+K1REVv//3urQ0Kor1/RhiYiFRZO9mcjiR1EFzKZsYKF66JiUvzC2ATxkro1w0EwY8jgTRxK7JgfuonFKsY3V9Kkbx1rjFAiWQI9Q1lYVUmzxJcdRErwDhER02rRTZNiPRvNrCytRZzNC/px8n9h1tDX3hC0f3w/mmSAfqmpbFeh2thnY5N97W6JPT+umyd5LGlP6yPwZGjp88JQOhAynYJ2MZa/zrmh9ReMuivteynmD+QqcS2jz6X7z1FpVVgfjQT9WhDLG0N8E8c/r/+xu3QPm6Jja45Z2aCS2Img+uPA7+KwaiFd6S8MWb3jGLiheSmZBW6pM+rHJb9SfUVRkGWgl+ZOViikQhP9Cumgv4sViCDdDqihU/5i10UeoRo1qRJoazu/6VV4HsVWlzTOu13QMoKnlX34+aX94dopKgVdsxQ17EV5zhvmVgmtDkCvVBJ700mY7xO2VxULs8Xm34yQSK4YSdzQL82wvot+ayi0301UTZM/pHv8LSMKz/4RbKL23QjcUvmm1zqqxDC+OKTy6Y/m1ZuLaNvjIDcfKjS6SraqKwxR+9Zj6GS+xkruEMT5yqlJnXWPxIuZ5HaoGFhepUOD78UVpYPH3dHxVgmIp6JbefG0cucYSY3I4bNxHeqbsmJMuqFgLaIK5F2qVnMWwYpECIj7UEIMhO+IvbuvYK7jBuoVkioGZOYyzZcjh0qjwB5Q8l8
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: enpace-registry
      namespace: {{ .Release.Namespace}}